import type {
  EnemyDefinition,
  OfficialEnemyKind,
  MapDefinition,
  OfficialMapKind,
  ModeDefinition,
  Point,
  TowerDefinition,
  TowerKind,
} from "./types.ts";

export const WORLD_WIDTH = 1600;
export const WORLD_HEIGHT = 700;
export const PATH_HALF_WIDTH = 50;
export const DEFAULT_MULTIPLAYER_HIT_CASH_MULTIPLIER = 0.75;
export const RANGE_SCALE = 15;
export const MAP_SCALE_MIN = 0.4;
export const MAP_SCALE_MAX = 2;
export const DEFAULT_MAP_SCALE = 1;

export const PATH: readonly Point[] = [
  { x: -35, y: 360 },
  { x: 200, y: 360 },
  { x: 200, y: 100 },
  { x: 530, y: 100 },
  { x: 530, y: 600 },
  { x: 880, y: 600 },
  { x: 880, y: 190 },
  { x: 1240, y: 190 },
  { x: 1240, y: 500 },
  { x: 1635, y: 500 },
] as const;

/** Built-in official roster. Only maps packaged here are global and read-only. */
export const MAP_DEFINITIONS: Record<OfficialMapKind, MapDefinition> = {
  sector07: {
    kind: "sector07",
    name: "Sector 07-A",
    index: 1,
    isCustom: false,
    difficulty: "Easy",
    description: "A long industrial route with generous corners and balanced build space.",
    rewardMultiplier: 1,
    mapScale: DEFAULT_MAP_SCALE,
    path: PATH,
    core: { x: 1525, y: 500 },
    entryLabel: { x: 100, y: 424 },
    pathLabel: { x: 780, y: 643 },
    blockedZones: [],
    palette: { field: "#0b0e0f", glow: "rgba(71,80,78,.13)", path: "#1b2021", accent: "#c3ceca" },
  },
  switchback: {
    kind: "switchback",
    name: "Ashen Switchback",
    index: 2,
    isCustom: false,
    difficulty: "Medium",
    description: "A shorter split-height route with fewer shared firing angles and riskier blocker support.",
    rewardMultiplier: 1.15,
    mapScale: DEFAULT_MAP_SCALE,
    path: [
      { x: -35, y: 110 }, { x: 370, y: 110 }, { x: 370, y: 590 }, { x: 830, y: 590 },
      { x: 830, y: 220 }, { x: 1240, y: 220 }, { x: 1240, y: 500 }, { x: 1635, y: 500 },
    ],
    core: { x: 1525, y: 500 },
    entryLabel: { x: 100, y: 174 },
    pathLabel: { x: 825, y: 643 },
    blockedZones: [],
    palette: { field: "#100d0c", glow: "rgba(130,73,48,.14)", path: "#29201c", accent: "#e2a06f" },
  },
  overpass: {
    kind: "overpass",
    name: "Null Overpass",
    index: 3,
    isCustom: false,
    difficulty: "Hard",
    description: "The shortest route: long isolated lanes deny loop coverage and punish late relocation.",
    rewardMultiplier: 1.3,
    mapScale: DEFAULT_MAP_SCALE,
    path: [
      { x: -35, y: 590 }, { x: 400, y: 590 }, { x: 400, y: 110 }, { x: 1010, y: 110 },
      { x: 1010, y: 500 }, { x: 1335, y: 500 }, { x: 1335, y: 260 }, { x: 1635, y: 260 },
    ],
    core: { x: 1525, y: 260 },
    entryLabel: { x: 100, y: 654 },
    pathLabel: { x: 795, y: 174 },
    blockedZones: [],
    palette: { field: "#0a0d13", glow: "rgba(65,82,145,.16)", path: "#171e2c", accent: "#8ca9ff" },
  },
};

/**
 * EDIT ENEMIES HERE.
 *
 * Every enemy owns its gameplay stats and its canvas sprite assignment. `hp` is
 * real base health: changing it directly changes every spawned copy. Normal Mode
 * uses these values as-is; there is no hidden endless scaling.
 */
export const ENEMY_DEFINITIONS: Record<OfficialEnemyKind, EnemyDefinition> = {
  dummy: {
    kind: "dummy",
    name: "Dummy",
    hp: 4,
    shieldHp: 0,
    speed: 42,
    damage: 3,
    attackInterval: 1.72,
    telegraphDuration: 0.86,
    coreDamage: 1,
    radius: 12,
    sprite: {
      shape: "square",
      fill: "#e8dfc7",
      stroke: "#7a6747",
      accent: "#ffc761",
      glyph: "D",
    },
  },
  speedy: {
    kind: "speedy",
    name: "Speedy",
    hp: 3,
    shieldHp: 0,
    speed: 62,
    damage: 2,
    attackInterval: 1.25,
    telegraphDuration: 0.64,
    coreDamage: 1,
    radius: 11,
    sprite: {
      shape: "diamond",
      fill: "#83ddd3",
      stroke: "#285f65",
      accent: "#b5fff1",
      glyph: "S",
    },
  },
  slow: {
    kind: "slow",
    name: "Slow",
    hp: 20,
    shieldHp: 0,
    speed: 25,
    damage: 6,
    attackInterval: 2.2,
    telegraphDuration: 1.08,
    coreDamage: 1,
    radius: 16,
    sprite: {
      shape: "hexagon",
      fill: "#d5a85e",
      stroke: "#765326",
      accent: "#ffe09a",
      glyph: "S",
    },
  },
  rusher: {
    kind: "rusher",
    name: "Rusher",
    hp: 17,
    shieldHp: 0,
    speed: 78,
    damage: 4,
    attackInterval: 1.05,
    telegraphDuration: 0.55,
    coreDamage: 1,
    radius: 13,
    sprite: {
      shape: "diamond",
      fill: "#e86f68",
      stroke: "#7e2f34",
      accent: "#ffaaa2",
      glyph: "R",
    },
  },
  dummyBoss: {
    kind: "dummyBoss",
    name: "Dummy Boss",
    hp: 120,
    shieldHp: 0,
    speed: 29,
    damage: 10,
    attackInterval: 2.15,
    telegraphDuration: 1.05,
    coreDamage: 2,
    radius: 20,
    boss: true,
    sprite: {
      shape: "square",
      fill: "#efc95f",
      stroke: "#805f23",
      accent: "#fff0a3",
      glyph: "DB",
    },
  },
  transparentDummy: {
    kind: "transparentDummy",
    name: "Transparent Dummy",
    hp: 8,
    shieldHp: 0,
    speed: 56,
    damage: 3,
    attackInterval: 1.4,
    telegraphDuration: 0.68,
    coreDamage: 1,
    radius: 13,
    hidden: true,
    sprite: {
      shape: "square",
      fill: "rgba(96,214,239,.42)",
      stroke: "#57d8ee",
      accent: "#bdf8ff",
      glyph: "H",
    },
  },
  tough: {
    kind: "tough",
    name: "Tough",
    hp: 50,
    shieldHp: 0,
    speed: 36,
    damage: 7,
    attackInterval: 1.9,
    telegraphDuration: 0.92,
    coreDamage: 2,
    radius: 17,
    sprite: {
      shape: "hexagon",
      fill: "#73bd70",
      stroke: "#315f38",
      accent: "#bdffae",
      glyph: "T",
    },
  },
  dummymancer: {
    kind: "dummymancer",
    name: "Dummymancer",
    hp: 300,
    shieldHp: 0,
    speed: 23,
    damage: 8,
    attackInterval: 2.3,
    telegraphDuration: 1.1,
    coreDamage: 3,
    radius: 21,
    boss: true,
    summon: { interval: 9, count: 2, kinds: ["dummy", "speedy", "slow", "rusher"] },
    sprite: {
      shape: "diamond",
      fill: "#9d71d2",
      stroke: "#513574",
      accent: "#ddb6ff",
      glyph: "DM",
    },
  },
  necromancerBoss: {
    kind: "necromancerBoss",
    name: "Necromancer Boss",
    hp: 1750,
    shieldHp: 0,
    speed: 19,
    damage: 16,
    attackInterval: 2.5,
    telegraphDuration: 1.18,
    coreDamage: 5,
    radius: 28,
    boss: true,
    summon: { interval: 6.5, count: 6, kinds: ["dummy", "tough", "slow", "rusher"] },
    sprite: {
      shape: "diamond",
      fill: "#b84fc8",
      stroke: "#552060",
      accent: "#fa9cff",
      glyph: "NEC",
    },
  },
  slowBoss: {
    kind: "slowBoss",
    name: "Slow Boss",
    hp: 1000,
    shieldHp: 0,
    speed: 16,
    damage: 18,
    attackInterval: 2.7,
    telegraphDuration: 1.25,
    coreDamage: 4,
    radius: 25,
    boss: true,
    sprite: {
      shape: "hexagon",
      fill: "#be813e",
      stroke: "#684019",
      accent: "#ffd083",
      glyph: "SB",
    },
  },
  transparentBoss: {
    kind: "transparentBoss",
    name: "Transparent Boss",
    hp: 600,
    shieldHp: 0,
    speed: 42,
    damage: 14,
    attackInterval: 2,
    telegraphDuration: 0.92,
    coreDamage: 4,
    radius: 23,
    hidden: true,
    boss: true,
    sprite: {
      shape: "hexagon",
      fill: "rgba(64,192,232,.38)",
      stroke: "#4bdcf2",
      accent: "#bdf8ff",
      glyph: "HB",
    },
  },
  eliteRusher: {
    kind: "eliteRusher",
    name: "Elite Rusher",
    hp: 90,
    shieldHp: 0,
    speed: 82,
    damage: 9,
    attackInterval: 1,
    telegraphDuration: 0.52,
    coreDamage: 2,
    radius: 16,
    sprite: {
      shape: "diamond",
      fill: "#d93b48",
      stroke: "#6f1724",
      accent: "#ff8991",
      glyph: "ER",
    },
  },
  speedyBoss: {
    kind: "speedyBoss",
    name: "Speedy Boss",
    hp: 900,
    shieldHp: 0,
    speed: 88,
    damage: 20,
    attackInterval: 1.2,
    telegraphDuration: 0.58,
    coreDamage: 5,
    radius: 24,
    boss: true,
    sprite: {
      shape: "diamond",
      fill: "#35c8a1",
      stroke: "#17624f",
      accent: "#8affd5",
      glyph: "SP",
    },
  },
  toughBoss: {
    kind: "toughBoss",
    name: "Tough Boss",
    hp: 2000,
    shieldHp: 0,
    speed: 20,
    damage: 26,
    attackInterval: 2.6,
    telegraphDuration: 1.2,
    coreDamage: 6,
    radius: 28,
    boss: true,
    sprite: {
      shape: "hexagon",
      fill: "#3f8f58",
      stroke: "#1c4b2b",
      accent: "#85ef9e",
      glyph: "TB",
    },
  },
  bigDummy: {
    kind: "bigDummy",
    name: "Big Dummy",
    hp: 11500,
    shieldHp: 0,
    speed: 12,
    damage: 45,
    attackInterval: 3,
    telegraphDuration: 1.35,
    coreDamage: 12,
    radius: 34,
    boss: true,
    shockwave: { interval: 8, radius: 180, stunDuration: 2.4 },
    sprite: {
      shape: "hexagon",
      fill: "#d97832",
      stroke: "#713516",
      accent: "#ffca67",
      glyph: "BIG",
    },
  },
};

/** EDIT ECONOMY HERE: combat income, wave stipends, relocation, and casualty recovery. */
export const ECONOMY_RULES = {
  damageCashPerHp: 1,
  waveClearBase: 50,
  waveClearPerWave: 10,
  relocationCost: 200,
  casualtyRefundRate: 0.65,
} as const;

/** EDIT COMBAT TIMING HERE: universal reactive timing shared by every tower. */
export const COMBAT_RULES = {
  counterCooldown: 8,
  counterWindow: 0.42,
} as const;

/** EDIT TOWERS HERE: prices, stock, stats, forms, and every upgrade live together. */
export const TOWER_DEFINITIONS: Record<TowerKind, TowerDefinition> = {
  bandit: {
    kind: "bandit",
    name: "Bandit",
    glyph: "B",
    cost: 400,
    unlockCost: 0,
    copyLimit: 4,
    accent: "#e7b568",
    dimAccent: "#654a2d",
    hiddenDetectionLevel: 3,
    onPath: {
      title: "Highwayman",
      description: "Blocks enemies while alternating pistol fire with an inner-ring sword slash.",
      hp: 70,
      maxAggro: 2,
    },
    offPath: {
      title: "Gunslinger",
      description: "A medium-ranged starter whose sword controls enemies that enter its inner ring.",
    },
    counter: "QUICKDRAW - fires into every engaged enemy and immediately resets Bladeworks.",
    levels: [
      { damage: 2, fireRate: 1.2, range: 12, hpMultiplier: 1, aggroBonus: 0 },
      { damage: 3, fireRate: 1.2, range: 12, hpMultiplier: 1.08, aggroBonus: 0 },
      { damage: 3, fireRate: 1, range: 13, hpMultiplier: 1.18, aggroBonus: 1 },
      { damage: 3, fireRate: 1, range: 13, hpMultiplier: 1.28, aggroBonus: 1 },
      { damage: 9, fireRate: 1, range: 16, hpMultiplier: 1.55, aggroBonus: 2 },
    ],
    upgrades: [
      { level: 1, cost: 200, title: "Combat Ready", onPathSkill: "+1 damage.", offPathSkill: "+1 damage." },
      {
        level: 2,
        cost: 380,
        title: "Bladeworks",
        onPathSkill: "Attack rate becomes 1s and a 2x-damage frontal sword slash triggers every 3.5s.",
        offPathSkill: "Attack rate becomes 1s and gains an inner-ring 2x-damage sword slash every 3.5s.",
      },
      {
        level: 3,
        cost: 800,
        title: "Twinshot",
        onPathSkill: "Every pistol attack fires twice and gains hidden detection.",
        offPathSkill: "Every pistol attack fires twice and gains hidden detection.",
      },
      {
        level: 4,
        cost: 2000,
        title: "Combat Mastery",
        onPathSkill: "+6 damage, +3 range, and the sword slash rises to 18 damage.",
        offPathSkill: "+6 damage, +3 range, and the sword slash rises to 18 damage.",
      },
    ],
  },
  samurai: {
    kind: "samurai",
    name: "Samurai",
    glyph: "S",
    cost: 1400,
    unlockCost: 1600,
    copyLimit: 4,
    accent: "#f17878",
    dimAccent: "#6a3035",
    hiddenDetectionLevel: 0,
    onPath: {
      title: "Blade Stance",
      description: "A melee emergency specialist that attacks only during its charged 15-second stance.",
      hp: 135,
      maxAggro: 3,
    },
    offPath: {
      title: "Ronin",
      description: "Frontal area slashes with current-HP scaling; press Q when charged to draw the blade.",
    },
    counter: "IAI PARRY - cancels incoming blows with crossing spectral cuts against engaged enemies.",
    ability: {
      name: "Blade Stance",
      description: "Draw the blade for 15s; later levels add focus, HP scaling, Bladestorm, and Demonblade.",
      unlockLevel: 0,
      cooldown: 30,
    },
    levels: [
      { damage: 12, fireRate: 0.7, range: 9, hpMultiplier: 1, aggroBonus: 0 },
      { damage: 16, fireRate: 0.7, range: 9, hpMultiplier: 1.1, aggroBonus: 0 },
      { damage: 18, fireRate: 0.7, range: 9, hpMultiplier: 1.25, aggroBonus: 1 },
      { damage: 32, fireRate: 0.7, range: 9, hpMultiplier: 1.5, aggroBonus: 1 },
      { damage: 32, fireRate: 0.9, range: 9, hpMultiplier: 1.8, aggroBonus: 2 },
      { damage: 232, fireRate: 0.9, range: 9, hpMultiplier: 2.4, aggroBonus: 3 },
    ],
    upgrades: [
      {
        level: 1,
        cost: 900,
        title: "Mental Focus",
        onPathSkill: "+4 damage; stores 2% attack-rate focus per charged second, up to 60%.",
        offPathSkill: "+4 damage; stores 2% attack-rate focus per charged second, up to 60%.",
      },
      {
        level: 2,
        cost: 1500,
        title: "Sensing Weakness",
        onPathSkill: "+2 damage and +2% target current-HP damage, capped at 3x base attack damage.",
        offPathSkill: "+2 damage and +2% target current-HP damage, capped at 3x base attack damage.",
      },
      {
        level: 3,
        cost: 5800,
        title: "Bladestorm",
        onPathSkill: "+14 damage; drawing the blade deals a 10x area strike and focus can reach 100%.",
        offPathSkill: "+14 damage; drawing the blade deals a 10x area strike and focus can reach 100%.",
      },
      {
        level: 4,
        cost: 8500,
        title: "Demonblade",
        onPathSkill: "Can attack without Blade Stance; stance grants +50% damage and HP scaling rises to 10%.",
        offPathSkill: "Can attack without Blade Stance; stance grants +50% damage and HP scaling rises to 10%.",
      },
      {
        level: 5,
        cost: 18000,
        title: "Cut Life and Soul",
        onPathSkill: "Adds 200 split damage, raises scaling cap to 6x, and Blade Stance grants +100% damage.",
        offPathSkill: "Adds 200 split damage, raises scaling cap to 6x, and Blade Stance grants +100% damage.",
      },
    ],
  },
  tempest: {
    kind: "tempest",
    name: "Tempest",
    glyph: "T",
    cost: 2000,
    unlockCost: 2400,
    copyLimit: 4,
    accent: "#9ae9ff",
    dimAccent: "#315d6a",
    onPath: {
      title: "Lightning Field",
      description: "A very short-range two-hit electric support that groups enemies with powerful Shock.",
      hp: 150,
      maxAggro: 1,
    },
    offPath: {
      title: "Storm Conduit",
      description: "Creates a current-HP lightning field on placement and whenever it is upgraded.",
    },
    counter: "THUNDER BREAK - creates or extends the Lightning Field and shocks nearby enemies.",
    levels: [
      { damage: 10, fireRate: 2, range: 5, hpMultiplier: 1, aggroBonus: 0 },
      { damage: 12, fireRate: 2, range: 5, hpMultiplier: 1.1, aggroBonus: 0 },
      { damage: 22, fireRate: 2, range: 5, hpMultiplier: 1.25, aggroBonus: 1 },
      { damage: 40, fireRate: 2, range: 5, hpMultiplier: 1.5, aggroBonus: 1 },
      { damage: 40, fireRate: 2, range: 5, hpMultiplier: 1.75, aggroBonus: 2 },
      { damage: 40, fireRate: 2, range: 5, hpMultiplier: 1.85, aggroBonus: 2 },
    ],
    upgrades: [
      {
        level: 1,
        cost: 800,
        title: "Thunder Break",
        onPathSkill: "+2 damage and immediately creates a Lightning Field.",
        offPathSkill: "+2 damage and immediately creates a Lightning Field.",
      },
      {
        level: 2,
        cost: 2000,
        title: "Static Gauntlets",
        onPathSkill: "+10 damage; attacks gain small area damage and apply 50% Shock.",
        offPathSkill: "+10 damage; attacks gain small area damage and apply 50% Shock.",
      },
      {
        level: 3,
        cost: 8000,
        title: "Lightning Charge",
        onPathSkill: "+18 damage; every sixth attack creates a Lightning Field.",
        offPathSkill: "+18 damage; every sixth attack creates a Lightning Field.",
      },
      {
        level: 4,
        cost: 10650,
        title: "Eye of the Storm",
        onPathSkill: "Attack area doubles and Shock begins at 90% slow with much lower decay.",
        offPathSkill: "Attack area doubles and Shock begins at 90% slow with much lower decay.",
      },
      {
        level: 5,
        cost: 0,
        title: "Flasharc",
        onPathSkill: "Lightning Field duration increases from 6s to 9s.",
        offPathSkill: "Lightning Field duration increases from 6s to 9s.",
      },
    ],
  },
  cyborg: {
    kind: "cyborg",
    name: "Cyborg",
    glyph: "C",
    cost: 700,
    unlockCost: 1800,
    copyLimit: 4,
    accent: "#f1f4f2",
    dimAccent: "#5d6562",
    hiddenDetectionLevel: 1,
    onPath: {
      title: "Heavy Burst",
      description: "Blocks a small group while emptying a rapid magazine before reloading.",
      hp: 95,
      maxAggro: 2,
    },
    offPath: {
      title: "Cyber-Penetration",
      description: "A ranged generalist with magazines, firing ramp, explosive final shots, and rockets.",
    },
    counter: "MAGNUM DUMP - unloads the current magazine into engaged enemies and primes the Howitzer.",
    levels: [
      { damage: 1, fireRate: 0.2, range: 14, hpMultiplier: 1, aggroBonus: 0, ammo: 15, reload: 3 },
      { damage: 1, fireRate: 0.15, range: 14, hpMultiplier: 1.1, aggroBonus: 0, ammo: 15, reload: 2 },
      { damage: 2, fireRate: 0.15, range: 17, hpMultiplier: 1.2, aggroBonus: 1, ammo: 20, reload: 2 },
      { damage: 2, fireRate: 0.15, range: 17, hpMultiplier: 1.35, aggroBonus: 1, ammo: 20, reload: 2 },
      { damage: 3, fireRate: 0.3, range: 17, hpMultiplier: 1.65, aggroBonus: 2 },
      { damage: 5, fireRate: 0.3, range: 21, hpMultiplier: 2.1, aggroBonus: 2 },
    ],
    upgrades: [
      {
        level: 1,
        cost: 375,
        title: "Scanner",
        onPathSkill: "Gains hidden detection; attack rate improves to 0.15s and reload drops to 2s.",
        offPathSkill: "Gains hidden detection; attack rate improves to 0.15s and reload drops to 2s.",
      },
      {
        level: 2,
        cost: 1100,
        title: "Overclock",
        onPathSkill: "+1 damage, +3 range, and magazine size increases from 15 to 20.",
        offPathSkill: "+1 damage, +3 range, and magazine size increases from 15 to 20.",
      },
      {
        level: 3,
        cost: 1500,
        title: "Magnum Howitzer",
        onPathSkill: "Fire rate ramps while attacking; the final magazine shot deals 10x area damage.",
        offPathSkill: "Fire rate ramps while attacking; the final magazine shot deals 10x area damage.",
      },
      {
        level: 4,
        cost: 3150,
        title: "Reactor System",
        onPathSkill: "+1 damage, removes reloads, and fires a 10x Howitzer every 30 shots.",
        offPathSkill: "+1 damage, removes reloads, and fires a 10x Howitzer every 30 shots.",
      },
      {
        level: 5,
        cost: 15250,
        title: "Jetstream",
        onPathSkill: "+2 damage, +4 range, Howitzer every 20 shots, and three 140-damage rockets every 8s with 1s between shots.",
        offPathSkill: "+2 damage, +4 range, Howitzer every 20 shots, and three 140-damage rockets every 8s with 1s between shots.",
      },
    ],
  },
  mercenary: {
    kind: "mercenary",
    name: "Mercenary",
    glyph: "M",
    cost: 1000,
    unlockCost: 1200,
    copyLimit: 4,
    accent: "#d8c18b",
    dimAccent: "#655a3d",
    hiddenDetectionLevel: 2,
    onPath: {
      title: "Vanguard Contract",
      description: "A durable rifleman who blocks enemies and can rally nearby constructs with Onslaught.",
      hp: 115,
      maxAggro: 3,
    },
    offPath: {
      title: "Field Emissary",
      description: "An efficient physical rifleman whose late upgrades unlock a large-area damage buff.",
    },
    counter: "RALLY FIRE - marks and shoots every engaged enemy with a coordinated rifle volley.",
    ability: {
      name: "Onslaught",
      description: "Buffs nearby towers by 25% damage for 8s; Level 6 improves it to 35% for 10s.",
      unlockLevel: 5,
      cooldown: 40,
    },
    levels: [
      { damage: 5, fireRate: 1.2, range: 12, hpMultiplier: 1, aggroBonus: 0 },
      { damage: 7, fireRate: 1.2, range: 12, hpMultiplier: 1.08, aggroBonus: 0 },
      { damage: 7, fireRate: 1.2, range: 15, hpMultiplier: 1.16, aggroBonus: 1 },
      { damage: 7, fireRate: 0.45, range: 15, hpMultiplier: 1.3, aggroBonus: 1 },
      { damage: 11, fireRate: 0.45, range: 17, hpMultiplier: 1.45, aggroBonus: 1 },
      { damage: 11, fireRate: 0.22, range: 20, hpMultiplier: 1.7, aggroBonus: 2 },
      { damage: 13, fireRate: 0.14, range: 20, hpMultiplier: 2, aggroBonus: 2 },
    ],
    upgrades: [
      { level: 1, cost: 550, title: "Firepower", onPathSkill: "+2 damage.", offPathSkill: "+2 damage." },
      { level: 2, cost: 700, title: "Pursuit", onPathSkill: "+3 range and hidden detection.", offPathSkill: "+3 range and hidden detection." },
      { level: 3, cost: 1750, title: "Assault", onPathSkill: "Attack rate improves from 1.2s to 0.45s.", offPathSkill: "Attack rate improves from 1.2s to 0.45s." },
      { level: 4, cost: 2000, title: "Exterminate", onPathSkill: "+4 damage and +2 range.", offPathSkill: "+4 damage and +2 range." },
      { level: 5, cost: 6500, title: "Emissary", onPathSkill: "+3 range, 0.22s attack rate, and unlocks 25% Onslaught.", offPathSkill: "+3 range, 0.22s attack rate, and unlocks 25% Onslaught." },
      { level: 6, cost: 10000, title: "Onrush", onPathSkill: "+2 damage, 0.14s attack rate, and Onslaught improves to 35%.", offPathSkill: "+2 damage, 0.14s attack rate, and Onslaught improves to 35%." },
    ],
  },
  infernus: {
    kind: "infernus",
    name: "Infernus",
    glyph: "I",
    cost: 750,
    unlockCost: 700,
    copyLimit: 4,
    accent: "#ff8a4c",
    dimAccent: "#713a28",
    onPath: {
      title: "Firebreak",
      description: "Blocks the road while projecting a continuous cone of flames that burns and slows crowds.",
      hp: 90,
      maxAggro: 1,
    },
    offPath: {
      title: "Flame Projector",
      description: "Prioritizes unburned enemies and paints its cone with persistent, non-stacking fire.",
    },
    counter: "FLASHOVER - ignites every engaged enemy and blasts a wide flame cone.",
    levels: [
      { damage: 0, fireRate: 0.25, range: 11, hpMultiplier: 1, aggroBonus: 0 },
      { damage: 1, fireRate: 0.25, range: 11, hpMultiplier: 1.1, aggroBonus: 0 },
      { damage: 1, fireRate: 0.25, range: 11, hpMultiplier: 1.2, aggroBonus: 1 },
      { damage: 2, fireRate: 0.25, range: 11, hpMultiplier: 1.35, aggroBonus: 1 },
      { damage: 2, fireRate: 0.25, range: 11, hpMultiplier: 1.55, aggroBonus: 2 },
      { damage: 4, fireRate: 0.25, range: 11, hpMultiplier: 1.9, aggroBonus: 2 },
    ],
    upgrades: [
      { level: 1, cost: 500, title: "Bigger Flames", onPathSkill: "+1 direct damage and a wider cone.", offPathSkill: "+1 direct damage and a wider cone." },
      { level: 2, cost: 850, title: "Napalm Fire", onPathSkill: "Burn lasts 6s and slows enemies by 15%.", offPathSkill: "Burn lasts 6s and slows enemies by 15%." },
      { level: 3, cost: 1450, title: "Blazing Arson", onPathSkill: "+1 direct damage and burn rises to 3 damage.", offPathSkill: "+1 direct damage and burn rises to 3 damage." },
      { level: 4, cost: 2250, title: "The Furnace", onPathSkill: "Burn rises to 4 damage and ticks every 0.5s.", offPathSkill: "Burn rises to 4 damage and ticks every 0.5s." },
      { level: 5, cost: 7500, title: "Absolute Hellfire", onPathSkill: "10s burn, 10 burn damage, +2 direct damage, and 25% slow.", offPathSkill: "10s burn, 10 burn damage, +2 direct damage, and 25% slow." },
    ],
  },
  bomber: {
    kind: "bomber",
    name: "Bomber",
    glyph: "BO",
    cost: 700,
    unlockCost: 1400,
    copyLimit: 4,
    accent: "#ffd36a",
    dimAccent: "#6c5730",
    hiddenDetectionLevel: 2,
    onPath: {
      title: "Tracklayer",
      description: "Plants explosive charges directly on the route while blocking a small hostile group.",
      hp: 82,
      maxAggro: 1,
    },
    offPath: {
      title: "Demolitionist",
      description: "Throws area bombs, deals bonus damage to burning enemies, and unlocks Time Bomb.",
    },
    counter: "DEAD MAN'S SWITCH - detonates a heavy bomb among engaged enemies.",
    ability: {
      name: "Time Bomb",
      description: "Throws a bomb that detonates after 5s for 500 area damage.",
      unlockLevel: 4,
      cooldown: 60,
    },
    levels: [
      { damage: 4, fireRate: 2, range: 11, hpMultiplier: 1, aggroBonus: 0 },
      { damage: 5, fireRate: 2, range: 11, hpMultiplier: 1.08, aggroBonus: 0 },
      { damage: 7, fireRate: 2, range: 11, hpMultiplier: 1.18, aggroBonus: 1 },
      { damage: 10, fireRate: 2, range: 14, hpMultiplier: 1.32, aggroBonus: 1 },
      { damage: 15, fireRate: 1.5, range: 14, hpMultiplier: 1.5, aggroBonus: 2 },
      { damage: 22, fireRate: 1.5, range: 14, hpMultiplier: 1.75, aggroBonus: 2 },
    ],
    upgrades: [
      { level: 1, cost: 550, title: "More Gunpowder", onPathSkill: "+1 damage, wider explosions, and 2x damage to burning enemies.", offPathSkill: "+1 damage, wider explosions, and 2x damage to burning enemies." },
      { level: 2, cost: 1000, title: "Explosive Arsenal", onPathSkill: "+2 damage and hidden detection.", offPathSkill: "+2 damage and hidden detection." },
      { level: 3, cost: 3000, title: "Dynamites", onPathSkill: "+3 damage/range; every fourth bomb deals 3x damage.", offPathSkill: "+3 damage/range; every fourth bomb deals 3x damage." },
      { level: 4, cost: 3500, title: "Timed Detonation", onPathSkill: "+5 damage, 1.5s rate, and unlocks the 500-damage Time Bomb.", offPathSkill: "+5 damage, 1.5s rate, and unlocks the 500-damage Time Bomb." },
      { level: 5, cost: 6000, title: "Critical Explosives", onPathSkill: "+7 damage and 3x damage against strong burns.", offPathSkill: "+7 damage and 3x damage against strong burns." },
    ],
  },
  recon: {
    kind: "recon",
    name: "Recon",
    glyph: "R",
    cost: 600,
    unlockCost: 1800,
    copyLimit: 4,
    accent: "#69e4d3",
    dimAccent: "#285f5b",
    hiddenDetectionLevel: 2,
    onPath: {
      title: "Breach Recon",
      description: "A pathbound Semi-Auto Shotgun operator with one aggro slot, piercing pellets, and a reactive breach load.",
      hp: 72,
      maxAggro: 1,
    },
    offPath: {
      title: "Semi-Auto Shotgun",
      description: "Fires five piercing pellets per shot from a five-shell magazine, then reloads for four seconds.",
    },
    counter: "BREACH LOAD - point-blank fires a full five-pellet shell through every engaged enemy and instantly chambers a fresh magazine.",
    levels: [
      { damage: 3, fireRate: 0.5, range: 6.4, hpMultiplier: 1, aggroBonus: 0, ammo: 5, reload: 4 },
      { damage: 3, fireRate: 0.4, range: 7.2, hpMultiplier: 1.08, aggroBonus: 0, ammo: 5, reload: 4 },
      { damage: 4, fireRate: 0.4, range: 7.2, hpMultiplier: 1.16, aggroBonus: 0, ammo: 5, reload: 4 },
      { damage: 8, fireRate: 0.4, range: 7.2, hpMultiplier: 1.28, aggroBonus: 0, ammo: 5, reload: 4 },
      { damage: 14, fireRate: 0.4, range: 8.8, hpMultiplier: 1.42, aggroBonus: 0, ammo: 5, reload: 4 },
      { damage: 23.8, fireRate: 0.35, range: 9.6, hpMultiplier: 1.6, aggroBonus: 0, ammo: 5, reload: 4 },
    ],
    upgrades: [
      { level: 1, cost: 300, title: "Faster Reload", onPathSkill: "+0.8 range and fires every 0.4s.", offPathSkill: "+0.8 range and fires every 0.4s." },
      { level: 2, cost: 720, title: "Radio Signal", onPathSkill: "+1 pellet damage and hidden detection.", offPathSkill: "+1 pellet damage and hidden detection." },
      { level: 3, cost: 1860, title: "Heavy Shells", onPathSkill: "+4 pellet damage and stronger piercing shells.", offPathSkill: "+4 pellet damage and stronger piercing shells." },
      { level: 4, cost: 3840, title: "Shotgun Barrage", onPathSkill: "+6 pellet damage and +1.6 range while retaining five pellets per perk shot.", offPathSkill: "+6 pellet damage and +1.6 range while retaining five pellets per perk shot." },
      { level: 5, cost: 5400, title: "Expert Assassin", onPathSkill: "23.8 damage per pellet, +0.8 range, and a 0.35s firing interval.", offPathSkill: "23.8 damage per pellet, +0.8 range, and a 0.35s firing interval." },
    ],
  },
  gunner: {
    kind: "gunner",
    name: "Gunner",
    glyph: "G",
    cost: 350,
    unlockCost: 500,
    copyLimit: 4,
    accent: "#c7a0ff",
    dimAccent: "#564072",
    hiddenDetectionLevel: 3,
    onPath: {
      title: "Burst Guard",
      description: "A pathbound Ultraburst Gunner with one aggro slot and an emergency overclock counter.",
      hp: 76,
      maxAggro: 1,
    },
    offPath: {
      title: "Ultraburst Gunner",
      description: "Fires disciplined bursts; late levels accelerate by 2% with every bullet while contact is maintained.",
    },
    counter: "REDLINE RETURN - answers engaged enemies with a full burst and immediately adds 50% Ultraburst charge.",
    levels: [
      { damage: 1, fireRate: 1.5, range: 10, hpMultiplier: 1, aggroBonus: 0 },
      { damage: 1, fireRate: 1.5, range: 12, hpMultiplier: 1.08, aggroBonus: 0 },
      { damage: 2, fireRate: 1, range: 12, hpMultiplier: 1.16, aggroBonus: 0 },
      { damage: 3, fireRate: 1, range: 14, hpMultiplier: 1.28, aggroBonus: 0 },
      { damage: 5, fireRate: 1.5, range: 15, hpMultiplier: 1.42, aggroBonus: 0 },
      { damage: 9, fireRate: 1.5, range: 15, hpMultiplier: 1.6, aggroBonus: 0 },
    ],
    upgrades: [
      { level: 1, cost: 150, title: "Precision", onPathSkill: "+2 range.", offPathSkill: "+2 range." },
      { level: 2, cost: 250, title: "Shredder Bullets", onPathSkill: "+1 damage and cooldown improves from 1.5s to 1s.", offPathSkill: "+1 damage and cooldown improves from 1.5s to 1s." },
      { level: 3, cost: 600, title: "Marksman Eye", onPathSkill: "+1 damage, +2 range, and hidden detection.", offPathSkill: "+1 damage, +2 range, and hidden detection." },
      { level: 4, cost: 2013, title: "Burst Pistols", onPathSkill: "+2 damage, +1 range, four-shot bursts, and Ultraburst charge lasts 18s.", offPathSkill: "+2 damage, +1 range, four-shot bursts, and Ultraburst charge lasts 18s." },
      { level: 5, cost: 4773, title: "Rapidfire Assault", onPathSkill: "+4 damage, six-shot bursts at 0.1s spacing, and Ultraburst charge lasts 22s.", offPathSkill: "+4 damage, six-shot bursts at 0.1s spacing, and Ultraburst charge lasts 22s." },
    ],
  },
  warrior: {
    kind: "warrior",
    name: "Warrior",
    glyph: "W",
    cost: 400,
    unlockCost: 100,
    copyLimit: 4,
    accent: "#b7c9ff",
    dimAccent: "#465273",
    hiddenDetectionLevel: 3,
    onPath: {
      title: "Shield Line",
      description: "A cheap melee blocker whose focused sword strikes stop one engaged enemy at a time.",
      hp: 125,
      maxAggro: 3,
    },
    offPath: {
      title: "Sellsword",
      description: "An untargetable short-range melee fighter with efficient damage and a late double strike.",
    },
    counter: "RIPOSTE - performs an empowered double arc against every enemy in front.",
    levels: [
      { damage: 3, fireRate: 0.6, range: 5, hpMultiplier: 1, aggroBonus: 0 },
      { damage: 5, fireRate: 0.6, range: 5, hpMultiplier: 1.12, aggroBonus: 0 },
      { damage: 8, fireRate: 0.6, range: 6, hpMultiplier: 1.25, aggroBonus: 1 },
      { damage: 14, fireRate: 0.6, range: 6, hpMultiplier: 1.45, aggroBonus: 1 },
      { damage: 26, fireRate: 0.7, range: 6, hpMultiplier: 1.8, aggroBonus: 2 },
    ],
    upgrades: [
      { level: 1, cost: 300, title: "Broadsword", onPathSkill: "+2 damage.", offPathSkill: "+2 damage." },
      { level: 2, cost: 700, title: "Sharpness", onPathSkill: "+3 damage, +1 range, and regenerates 7% max HP every 7s.", offPathSkill: "+3 damage, +1 range, and regenerates 7% max HP every 7s." },
      { level: 3, cost: 1200, title: "Ethereal Blade", onPathSkill: "+6 damage and hidden detection.", offPathSkill: "+6 damage and hidden detection." },
      { level: 4, cost: 3500, title: "Warrior Spirit", onPathSkill: "+12 damage, delayed single-target Double Strike, and an arrival AoE slash after moving.", offPathSkill: "+12 damage, delayed single-target Double Strike, and an arrival AoE slash after moving." },
    ],
  },
};

export const TOWER_ORDER = Object.keys(TOWER_DEFINITIONS) as TowerKind[];

/**
 * MODE 01 — NORMAL
 * Exact 25-wave enemy compositions from CTD's current Normal Mode table.
 * `referenceHealth` and `waveTimeSeconds` preserve the wiki values for editing
 * and UI context; this game ends a wave when every hostile is defeated.
 */
const NORMAL_MODE_WAVES = [
  { groups: [{ kind: "dummy", count: 4, gap: 2.1 }], message: "Dummies incoming! Prepare to defend.", referenceHealth: 16, waveTimeSeconds: 35 },
  { groups: [{ kind: "dummy", count: 7, gap: 1.8 }], referenceHealth: 28, waveTimeSeconds: 35 },
  { groups: [{ kind: "speedy", count: 7, gap: 1.1 }], message: "New fast dummies incoming.", referenceHealth: 12, waveTimeSeconds: 35 },
  { groups: [{ kind: "dummy", count: 5, gap: 1.5 }, { kind: "speedy", count: 3, gap: 1 }], referenceHealth: 29, waveTimeSeconds: 35 },
  { groups: [{ kind: "slow", count: 4, gap: 2.1 }], message: "Stronger dummies incoming!", referenceHealth: 80, waveTimeSeconds: 35 },
  { groups: [{ kind: "dummy", count: 4, gap: 1.4 }, { kind: "slow", count: 5, gap: 1.8 }], referenceHealth: 116, waveTimeSeconds: 35 },
  { groups: [{ kind: "dummy", count: 7, gap: 1.1 }, { kind: "speedy", count: 10, gap: 0.72 }], referenceHealth: 58, waveTimeSeconds: 35 },
  { groups: [{ kind: "rusher", count: 6, gap: 1.05 }], message: "Another fast enemy is approaching!", referenceHealth: 102, waveTimeSeconds: 35 },
  { groups: [{ kind: "dummy", count: 4, gap: 1.1 }, { kind: "slow", count: 3, gap: 1.55 }, { kind: "rusher", count: 5, gap: 0.78 }], referenceHealth: 161, waveTimeSeconds: 35 },
  { groups: [{ kind: "dummy", count: 6, gap: 1.05 }, { kind: "dummyBoss", count: 1, gap: 2 }], message: "A boss has been spotted!", referenceHealth: 144, waveTimeSeconds: 40 },
  { groups: [{ kind: "rusher", count: 7, gap: 0.75 }, { kind: "slow", count: 5, gap: 1.4 }], referenceHealth: 219, waveTimeSeconds: 40 },
  { groups: [{ kind: "slow", count: 5, gap: 1.35 }, { kind: "rusher", count: 10, gap: 0.68 }, { kind: "dummyBoss", count: 1, gap: 2 }], message: "Transparent dummies are coming next wave.", referenceHealth: 390, waveTimeSeconds: 40 },
  { groups: [{ kind: "transparentDummy", count: 7, gap: 1 }], message: "Hidden enemies! Only towers with detection can target them.", referenceHealth: 56, waveTimeSeconds: 40 },
  { groups: [{ kind: "dummyBoss", count: 1, gap: 1.8 }, { kind: "rusher", count: 9, gap: 0.68 }, { kind: "speedy", count: 8, gap: 0.62 }], referenceHealth: 297, waveTimeSeconds: 40 },
  { groups: [{ kind: "tough", count: 6, gap: 1 }, { kind: "dummyBoss", count: 2, gap: 1.6 }, { kind: "slow", count: 4, gap: 1.25 }, { kind: "dummy", count: 3, gap: 0.9 }], referenceHealth: 636, waveTimeSeconds: 40 },
  { groups: [{ kind: "slow", count: 6, gap: 1.1 }, { kind: "tough", count: 5, gap: 0.95 }, { kind: "dummyBoss", count: 1, gap: 1.5 }, { kind: "dummymancer", count: 1, gap: 2 }], message: "A summoner is incoming.", referenceHealth: 936, waveTimeSeconds: 50 },
  { groups: [{ kind: "slow", count: 10, gap: 1 }, { kind: "dummyBoss", count: 5, gap: 1.25 }], referenceHealth: 800, waveTimeSeconds: 50 },
  { groups: [{ kind: "dummyBoss", count: 4, gap: 1.15 }, { kind: "transparentDummy", count: 10, gap: 0.65 }, { kind: "tough", count: 7, gap: 0.8 }, { kind: "slowBoss", count: 1, gap: 2 }], message: "A massive boss is incoming!", referenceHealth: 1910, waveTimeSeconds: 50 },
  { groups: [{ kind: "rusher", count: 6, gap: 0.72 }, { kind: "tough", count: 7, gap: 0.88 }, { kind: "dummyBoss", count: 1, gap: 1.6 }, { kind: "necromancerBoss", count: 1, gap: 2.2 }], message: "The Necromancer Boss is raising an army!", referenceHealth: 2322, waveTimeSeconds: 70 },
  { groups: [{ kind: "rusher", count: 3, gap: 0.62 }, { kind: "tough", count: 7, gap: 0.75 }, { kind: "transparentDummy", count: 9, gap: 0.62 }, { kind: "transparentBoss", count: 1, gap: 2 }], message: "A Transparent Boss is incoming!", referenceHealth: 1073, waveTimeSeconds: 60 },
  { groups: [{ kind: "dummyBoss", count: 3, gap: 1.05 }, { kind: "tough", count: 5, gap: 0.72 }, { kind: "slowBoss", count: 2, gap: 1.7 }, { kind: "dummymancer", count: 2, gap: 1.5 }], referenceHealth: 3210, waveTimeSeconds: 100 },
  { groups: [{ kind: "transparentBoss", count: 1, gap: 1.6 }, { kind: "tough", count: 3, gap: 0.72 }, { kind: "eliteRusher", count: 2, gap: 0.7 }, { kind: "speedyBoss", count: 1, gap: 2 }], message: "An extremely strong and fast enemy is approaching.", referenceHealth: 1830, waveTimeSeconds: 60 },
  { groups: [{ kind: "eliteRusher", count: 9, gap: 0.56 }, { kind: "slowBoss", count: 2, gap: 1.4 }, { kind: "tough", count: 10, gap: 0.62 }, { kind: "dummyBoss", count: 3, gap: 1 }, { kind: "dummymancer", count: 1, gap: 1.6 }], referenceHealth: 3970, waveTimeSeconds: 60 },
  { groups: [{ kind: "transparentDummy", count: 10, gap: 0.58 }, { kind: "transparentBoss", count: 2, gap: 1.1 }, { kind: "slowBoss", count: 2, gap: 1.4 }, { kind: "toughBoss", count: 1, gap: 2 }], message: "A Tough Boss is incoming!", referenceHealth: 5780, waveTimeSeconds: 300 },
  { groups: [{ kind: "dummyBoss", count: 9, gap: 0.8 }, { kind: "toughBoss", count: 1, gap: 1.4 }, { kind: "eliteRusher", count: 18, gap: 0.48 }, { kind: "bigDummy", count: 1, gap: 2 }], message: "The Big Dummy is here!", referenceHealth: 19950, waveTimeSeconds: null },
] as const;

export const NORMAL_MODE: ModeDefinition = {
  kind: "normal",
  name: "Normal Mode",
  index: 1,
  isCustom: false,
  description: "A finite 25-wave introductory campaign culminating in the Big Dummy.",
  startingCash: 500,
  coreIntegrity: 12,
  multiplayerHitCashMultiplier: DEFAULT_MULTIPLAYER_HIT_CASH_MULTIPLIER,
  reward: { coins: 160, tokens: 2 },
  waves: NORMAL_MODE_WAVES,
};

/** Add future finite modes here. The game never loops a mode's final wave. */
export const MODE_DEFINITIONS: readonly ModeDefinition[] = [NORMAL_MODE] as const;
